### ISSUE TITLE
Adauga-ma te rog in organizatia cnitv

### ISSUE THREAD

**Issue by tudurom** [CNITV/VianuEdu-Server#1]
Salut,

Eu si cu colegul meu @cirip scriem urmatoarea versiune pentru software-ul concursului Performante Vianiste, care se va tine marti. Vrem sa punem codul pe organizatia @CNITV pentru ca arata mai bine :)
Pentru asta, te rog sa ne adaugi pe amandoi in organizatie cu drepturi de adaugat repo-uri. O sa fie doua, unul client si unul server.

Am lasat un issue irelevant aici pentru ca alta metoda de comunicare nu am gasit. Daca ai vreun dubiu, domnul profesor Manz ne-a dat sarcina asta, poti sa il contactezi pe dumnealui.

**Comment by StormFireFox1** [comment]
Ai fost adaugat, impreuna cu colegul tau.

Data viitoare da-mi un e-mail :))
